import { BarChart3, Building, Heart, ShoppingCart, Smartphone, TrendingUp } from 'lucide-react';

const portfolioProjects = [
  {
    id: 1,
    name: 'MediCare Plus',
    client: 'Healthcare Clinic Network',
    category: 'Healthcare Platform',
    description:
      'A comprehensive patient management system with appointment scheduling, medical records, and telemedicine capabilities. Built to handle 10,000+ patients across multiple clinic locations.',
    image: '/placeholder.svg?height=400&width=600',
    completedDate: '2024',
    projectDuration: '8 months',
    teamSize: '4 developers',
    features: [
      'Patient Portal & Records',
      'Appointment Scheduling',
      'Telemedicine Integration',
      'Multi-clinic Management',
      'Insurance Processing',
      'GDPR Compliance',
      'Mobile App (iOS/Android)',
      'Real-time Notifications',
    ],
    technologies: ['React', 'Next.js', 'Spring Boot', 'PostgreSQL', 'Flutter', 'AWS'],
    results: [
      '50% reduction in appointment scheduling time',
      '30% increase in patient satisfaction',
      '99.9% system uptime achieved',
    ],
    gradient: 'from-blue-500 to-cyan-400',
    icon: Heart,
    liveUrl: '#',
    caseStudyUrl: '#',
  },
  {
    id: 2,
    name: 'EcoShop Croatia',
    client: 'Sustainable Products Retailer',
    category: 'E-commerce Platform',
    description:
      'A modern e-commerce platform focused on sustainable products with advanced inventory management, customer loyalty programs, and carbon footprint tracking for each purchase.',
    image: '/placeholder.svg?height=400&width=600',
    completedDate: '2024',
    projectDuration: '6 months',
    teamSize: '5 developers',
    features: [
      'Multi-vendor Marketplace',
      'Carbon Footprint Tracking',
      'Loyalty Rewards System',
      'Advanced Search & Filters',
      'Payment Gateway Integration',
      'Inventory Management',
      'Mobile-responsive Design',
      'Analytics Dashboard',
    ],
    technologies: ['React', 'Node.js', 'MongoDB', 'Stripe', 'AWS', 'Docker'],
    results: [
      '200% increase in online sales',
      '40% improvement in conversion rate',
      '15,000+ registered customers in first year',
    ],
    gradient: 'from-emerald-500 to-green-400',
    icon: ShoppingCart,
    liveUrl: '#',
    caseStudyUrl: '#',
  },
  {
    id: 3,
    name: 'DataViz Pro',
    client: 'Financial Services Company',
    category: 'Analytics Dashboard',
    description:
      'A real-time business intelligence dashboard that processes financial data from multiple sources, providing interactive visualizations and automated reporting for executive decision-making.',
    image: '/placeholder.svg?height=400&width=600',
    completedDate: '2023',
    projectDuration: '10 months',
    teamSize: '6 developers',
    features: [
      'Real-time Data Processing',
      'Interactive Dashboards',
      'Custom Report Builder',
      'Data Source Integration',
      'Automated Alerts',
      'Role-based Access Control',
      'Export Capabilities',
      'Mobile Dashboard App',
    ],
    technologies: ['React', 'Python', 'PostgreSQL', 'D3.js', 'Redis', 'Docker', 'AWS'],
    results: [
      '60% faster report generation',
      '90% reduction in manual data processing',
      'Enhanced decision-making speed by 40%',
    ],
    gradient: 'from-purple-500 to-pink-500',
    icon: BarChart3,
    liveUrl: '#',
    caseStudyUrl: '#',
  },
  {
    id: 4,
    name: 'CityGuide Mobile',
    client: 'Tourism Board Zagreb',
    category: 'Mobile Application',
    description:
      'A comprehensive city guide mobile app featuring interactive maps, augmented reality features, event listings, and offline capabilities for tourists visiting Zagreb.',
    image: '/placeholder.svg?height=400&width=600',
    completedDate: '2023',
    projectDuration: '7 months',
    teamSize: '4 developers',
    features: [
      'Interactive City Maps',
      'Augmented Reality Features',
      'Event Calendar',
      'Offline Map Access',
      'Multi-language Support',
      'Push Notifications',
      'Social Sharing',
      'Tourist Reviews & Ratings',
    ],
    technologies: ['Flutter', 'Dart', 'Firebase', 'Google Maps API', 'ARCore'],
    results: ['50,000+ downloads in first 6 months', '4.8/5 app store rating', '25% increase in tourist engagement'],
    gradient: 'from-orange-500 to-red-500',
    icon: Smartphone,
    liveUrl: '#',
    caseStudyUrl: '#',
  },
  {
    id: 5,
    name: 'EduManage System',
    client: 'Private School Network',
    category: 'Education Platform',
    description:
      'A comprehensive school management system handling student enrollment, grade tracking, parent communication, and administrative tasks across multiple school locations.',
    image: '/placeholder.svg?height=400&width=600',
    completedDate: '2022',
    projectDuration: '12 months',
    teamSize: '5 developers',
    features: [
      'Student Information System',
      'Grade & Attendance Tracking',
      'Parent-Teacher Communication',
      'Online Assignment Submission',
      'Financial Management',
      'Timetable Management',
      'Report Generation',
      'Mobile App for Parents',
    ],
    technologies: ['React', 'Spring Boot', 'MySQL', 'Flutter', 'AWS'],
    results: [
      '80% reduction in administrative workload',
      '95% parent satisfaction rate',
      'Streamlined operations across 5 schools',
    ],
    gradient: 'from-indigo-500 to-purple-500',
    icon: Building,
    liveUrl: '#',
    caseStudyUrl: '#',
  },
  {
    id: 6,
    name: 'FitTracker Pro',
    client: 'Fitness Center Chain',
    category: 'Fitness Platform',
    description:
      'A comprehensive fitness platform with member management, class scheduling, personal trainer booking, and nutrition tracking. Includes both web dashboard and mobile app.',
    image: '/placeholder.svg?height=400&width=600',
    completedDate: '2022',
    projectDuration: '9 months',
    teamSize: '4 developers',
    features: [
      'Member Management System',
      'Class Booking & Scheduling',
      'Personal Trainer Matching',
      'Workout & Nutrition Tracking',
      'Progress Analytics',
      'Payment Processing',
      'Social Features',
      'Wearable Device Integration',
    ],
    technologies: ['React', 'Node.js', 'MongoDB', 'Flutter', 'Stripe'],
    results: [
      '40% increase in member retention',
      '60% more class bookings',
      '35% growth in personal training sessions',
    ],
    gradient: 'from-green-500 to-teal-500',
    icon: TrendingUp,
    liveUrl: '#',
    caseStudyUrl: '#',
  },
];

export { portfolioProjects };
